[libdefaults]
    default_realm = ENTREPRISE.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    ENTREPRISE.LOCAL = {
        kdc = localhost:88
        admin_server = localhost:88
        default_domain = entreprise.local
    }

[domain_realm]
    .entreprise.local = ENTREPRISE.LOCAL
    entreprise.local = ENTREPRISE.LOCAL
